#!/bin/bash
# echo "DEBUG: ============== post-commit hook trap-card triggered! ==============" >&2
# ==============================================================================================
#                                         GIT LFS Hooks
# ==============================================================================================
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }

git lfs post-commit "$@"
# ==============================================================================================
#                                 Verify and Retrieve Dependencies
# ==============================================================================================
# Import code used in this script
FUNCTIONS_FILE="FreeCAD_Automation/utils.sh"
source "$FUNCTIONS_FILE"

if [ -z "$REQUIRE_LOCKS" ]; then
    echo "Error: Config file missing or invalid; cannot proceed." >&2
    exit $FAIL
fi

# ==============================================================================================
#                                   Set Readonly / Writable
# ==============================================================================================
if [ "$REQUIRE_LOCKS" = "$TRUE" ]; then
    CURRENT_USER="$(GIT_COMMAND="config" git config --get user.name)" || {
        echo "Error: git config user.name not set!" >&2
        exit $FAIL
    }

    mapfile -t CURRENT_LOCKS < <(
        GIT_COMMAND="lfs" git lfs locks |
        awk -v user="$CURRENT_USER" '
            match($0, /^(.*)[[:space:]]+([^[:space:]]+)[[:space:]]+ID:[0-9]+$/, m) &&
            m[2] == user {
                gsub(/[[:space:]]+$/, "", m[1])
                print m[1]
            }
        '
    ) || {
        echo "Error: failed to list of active lock info." >&2
        exit $FAIL
    }

    COMMITTED_CHANGEFILES="$(GIT_COMMAND="diff-tree" git diff-tree --no-commit-id --name-only -r HEAD | grep -i -- '\.changefile$')"

    mapfile -t COMMITTED_CHANGEFILES <<<"$COMMITTED_CHANGEFILES"
    for changefile in "${COMMITTED_CHANGEFILES[@]}"; do
        [ -z "$changefile" ] && continue
        
        # echo -e "\nDEBUG: checking '$changefile'....$(grep 'File Last Exported On:' "$changefile")" >&2
        FCStd_file_path="$(get_FCStd_file_from_changefile "$changefile")" || continue

        FCStd_dir_path="$(dirname "$changefile")"
        lockfile="$FCStd_dir_path/.lockfile"

        if printf '%s\n' "${CURRENT_LOCKS[@]}" | grep -Fxq -- "$lockfile"; then
            # User has lock, set .FCStd file to writable
            make_writable "$FCStd_file_path"
            # echo "DEBUG: set '$FCStd_file_path' writable." >&2
        else
            # User doesn't have lock, set .FCStd file to readonly
            make_readonly "$FCStd_file_path"
            # echo "DEBUG: set '$FCStd_file_path' readonly." >&2
        fi
    done
fi

exit $SUCCESS