#!/bin/bash
# ==============================================================================================
#                                 Verify and Retrieve Dependencies
# ==============================================================================================
# Check if inside a Git repository and ensure working dir is the root of the repo
if ! git rev-parse --git-dir > /dev/null; then
    echo "Error: Not inside a Git repository" >&2
    exit 1
fi

GIT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_ROOT"

# Import code used in this script
FUNCTIONS_FILE="FreeCAD_Automation/functions.sh"
source "$FUNCTIONS_FILE"

# ==============================================================================================
#                         Check if user allowed to modify .FCStd files
# ==============================================================================================
# Get staged .FCStd files
STAGED_FCSTD_FILES=$(git diff --cached --name-only | grep '\.FCStd$')
for file in $STAGED_FCSTD_FILES; do
    FCSTD_FILE_HAS_VALID_LOCK=$(FCStd_file_has_valid_lock "$file") || exit 1
    
    if [ $FCSTD_FILE_HAS_VALID_LOCK == 0 ]; then
        exit 1
    fi
done